config/routes.rb
Rails.application.routes.draw do
  resources :hold_points
  resources :messages
  resources :point_increases
  resources :users do
    resources :point_increases
    resources :point_decreases
    member do
      post "give_point"
      get "give_point/new", to: "users#give_point_new"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :point_increases
  has_many :point_decreases

  validate :point_must_be_zero_or_more

  def get_amount_of_point_increase
    self.point_increases.reduce(0) { |sum, point_increase | sum + point_increase.amount }
  end

  def get_amount_of_point_decrease
    self.point_decreases.reduce(0) { |sum, point_increase | sum + point_increase.amount }
  end

  def amount_of_point
    get_amount_of_point_increase - get_amount_of_point_decrease
  end

  def give_point_to(user, amount)
    PointDecrease.create(user_id: id, amount: amount)
    PointIncrease.create(user_id: user.id, amount: amount)
  end

  def name
    "#{last_name} #{first_name}"
  end

  private

  def point_must_be_zero_or_more
    if amount_of_point < 0
      errors.add(:base, "point must be zero or more")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # ポイント付与処理
  def give_point
    @user = User.find(params[:id])
    @sender = User.find(params[:sender_id])
    point_amount = params[:point_amount].to_i

    if point_amount > 0
      @sender.point_decreases.build(amount: point_amount).save!
      @user.point_increases.build(amount: point_amount).save!
      give_point = GivePoint.new(amount: point_amount, from_id: @sender.id, to_id: @user.id)
      give_point.save!
      Message.new(content: params[:message_content], from_id: @sender.id, to_id: @user.id, give_point_id: give_point.id).save!

      redirect_to @user, notice: "You sent points."
    else
      redirect_to @user, alert: "error while giving points."
    end
  end

  def give_point_new
    @user = User.find(params[:id])
    @from_users = User.where.not(id: @user.id)
    render :give_point_new
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:last_name, :first_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :last_name %>
      <%= form.text_field :last_name %>
    </div>

    <div>
      <%= form.label :first_name %>
      <%= form.text_field :first_name %>
    </div>


    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.last_name %> <%= user.first_name %>
  </p>

  <p>
    <strong>Point Increase:</strong>
    <%= user.get_amount_of_point_increase %>
  </p>

  <p>
    <strong>Point Decrease:</strong>
    <%= user.get_amount_of_point_decrease %>
  </p>

  <p>
    <strong>Amount of Point:</strong>
    <%= user.amount_of_point %>
  </p>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/give_point_new.html.erb
<h1>Give points to <%= @user.name %></h1>

<%= form_with url: give_point_user_path(@user), method: :post do |form| %>
  <div>
    <%= label_tag :point_amount, "giving point" %>
    <%= number_field_tag :point_amount, nil, min: 1 %>
    <div>
      <%= label_tag :sender_id, "sender" %>
      <%= select_tag :sender_id, options_from_collection_for_select(@from_users, :id, :name) %>
    </div>
    <div>
      <%= label_tag :message_content, "message" %>
      <%= form.text_area :message_content, name: "message_content" %>
    </div>
  </div>
  <div>
    <%= form.submit "ポイントを付与" %>
  </div>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %> |
      <%= link_to "ポイントを付与", give_point_new_user_path(user) %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %> |
  <%= link_to "ポイントを付与", give_point_new_user_path(@user), method: :post %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>