config/routes.rb
Rails.application.routes.draw do
  resources :hold_points
  resources :messages
  resources :point_increases
  resources :users do
    resources :point_increases
    resources :point_decreases
    member do
      post "give_point"
      get "give_point/new", to: "users#give_point_new"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/hold_point.rb
class HoldPoint < ApplicationRecord
end

app/controllers/hold_points_controller.rb
class HoldPointsController < ApplicationController
  before_action :set_hold_point, only: %i[ show edit update destroy ]

  # GET /hold_points or /hold_points.json
  def index
    @hold_points = HoldPoint.all
  end

  # GET /hold_points/1 or /hold_points/1.json
  def show
  end

  # GET /hold_points/new
  def new
    @hold_point = HoldPoint.new
  end

  # GET /hold_points/1/edit
  def edit
  end

  # POST /hold_points or /hold_points.json
  def create
    @hold_point = HoldPoint.new(hold_point_params)

    respond_to do |format|
      if @hold_point.save
        format.html { redirect_to @hold_point, notice: "Hold point was successfully created." }
        format.json { render :show, status: :created, location: @hold_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hold_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hold_points/1 or /hold_points/1.json
  def update
    respond_to do |format|
      if @hold_point.update(hold_point_params)
        format.html { redirect_to @hold_point, notice: "Hold point was successfully updated." }
        format.json { render :show, status: :ok, location: @hold_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hold_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hold_points/1 or /hold_points/1.json
  def destroy
    @hold_point.destroy!

    respond_to do |format|
      format.html { redirect_to hold_points_path, status: :see_other, notice: "Hold point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hold_point
      @hold_point = HoldPoint.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def hold_point_params
      params.fetch(:hold_point, {})
    end
end

app/helpers/hold_points_helper.rb
module HoldPointsHelper
end

app/views/hold_points/_form.html.erb
<%= form_with(model: hold_point) do |form| %>
  <% if hold_point.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hold_point.errors.count, "error") %> prohibited this hold_point from being saved:</h2>

      <ul>
        <% hold_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hold_points/_hold_point.html.erb
<div id="<%= dom_id hold_point %>">
</div>

app/views/hold_points/edit.html.erb
<% content_for :title, "Editing hold point" %>

<h1>Editing hold point</h1>

<%= render "form", hold_point: @hold_point %>

<br>

<div>
  <%= link_to "Show this hold point", @hold_point %> |
  <%= link_to "Back to hold points", hold_points_path %>
</div>

app/views/hold_points/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Hold points" %>

<h1>Hold points</h1>

<div id="hold_points">
  <% @hold_points.each do |hold_point| %>
    <%= render hold_point %>
    <p>
      <%= link_to "Show this hold point", hold_point %>
    </p>
  <% end %>
</div>

<%= link_to "New hold point", new_hold_point_path %>

app/views/hold_points/new.html.erb
<% content_for :title, "New hold point" %>

<h1>New hold point</h1>

<%= render "form", hold_point: @hold_point %>

<br>

<div>
  <%= link_to "Back to hold points", hold_points_path %>
</div>

app/views/hold_points/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hold_point %>

<div>
  <%= link_to "Edit this hold point", edit_hold_point_path(@hold_point) %> |
  <%= link_to "Back to hold points", hold_points_path %>

  <%= button_to "Destroy this hold point", @hold_point, method: :delete %>
</div>